In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

## Klasifikasi Menggunakan KNN hasil GLCM 0 Degree

In [2]:
# Baca file CSV yang berisi fitur GLCM dengan sudut 0 derajat
file_name = "../notebook/result/glcm_features_0_degree.csv"  
df = pd.read_csv(file_name)
print(df.head)

<bound method NDFrame.head of      contrast_0  homogeneity_0  correlation_0  energy_0  label
0    173.844805       0.805667       0.892292  0.156058      0
1     63.004537       0.865046       0.922682  0.166606      0
2     89.052386       0.837714       0.959530  0.176169      0
3    106.450134       0.835703       0.930860  0.143655      0
4    172.692754       0.811668       0.883358  0.205275      0
..          ...            ...            ...       ...    ...
170   41.435853       0.850722       0.907877  0.242152      4
171   65.079142       0.700208       0.956084  0.141597      4
172  216.525195       0.755399       0.844033  0.182967      4
173  103.922029       0.794540       0.877733  0.169511      4
174  113.289900       0.812024       0.919455  0.178411      4

[175 rows x 5 columns]>


In [3]:
# Pisahkan fitur (X) dan label kelas (y)
X = df.drop('label', axis=1) 
y = df['label']

In [4]:
# Bagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [5]:
# Inisialisasi model KNN
knn = KNeighborsClassifier(n_neighbors=4) 
# Latih model KNN
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [6]:
# Lakukan prediksi pada data uji
y_pred = knn.predict(X_test)

In [7]:
# Hitung dan tampilkan confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Tampilkan laporan klasifikasi
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(classification_rep)


Confusion Matrix:
[[7 2 1 0 0]
 [1 3 2 0 1]
 [1 3 0 2 0]
 [3 2 0 1 2]
 [1 1 0 0 2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.70      0.61        10
           1       0.27      0.43      0.33         7
           2       0.00      0.00      0.00         6
           3       0.33      0.12      0.18         8
           4       0.40      0.50      0.44         4

    accuracy                           0.37        35
   macro avg       0.31      0.35      0.31        35
weighted avg       0.33      0.37      0.33        35



## Klasifikasi Menggunakan KNN hasil GLCM 45 Degree

In [8]:
file_name = "../notebook/result/glcm_features_45_degree.csv" 
df = pd.read_csv(file_name)
print(df.head)

<bound method NDFrame.head of      contrast_45  homogeneity_45  correlation_45  energy_45  label
0     221.599345        0.771900        0.862952   0.149101      0
1     136.791043        0.796055        0.832516   0.147934      0
2     106.956690        0.796018        0.951538   0.161958      0
3     149.727050        0.777069        0.902978   0.128966      0
4     308.617062        0.759290        0.792139   0.187381      0
..           ...             ...             ...        ...    ...
170    78.559334        0.800985        0.825874   0.223593      4
171   136.775607        0.666513        0.907938   0.136636      4
172   340.062997        0.710755        0.755759   0.167671      4
173   186.203432        0.736305        0.781581   0.151505      4
174   174.928826        0.769867        0.876013   0.165096      4

[175 rows x 5 columns]>


In [9]:
# Pisahkan fitur (X) dan label kelas (y)
X = df.drop('label', axis=1) 
y = df['label']

In [10]:
# Bagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [11]:
# Inisialisasi model KNN
knn = KNeighborsClassifier(n_neighbors=4) 
# Latih model KNN
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [12]:
# Lakukan prediksi pada data uji
y_pred = knn.predict(X_test)

In [13]:
# Hitung dan tampilkan confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Tampilkan laporan klasifikasi
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(classification_rep)


Confusion Matrix:
[[4 0 3 2 1]
 [4 0 2 0 1]
 [2 1 2 1 0]
 [0 2 4 2 0]
 [1 0 0 3 0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.36      0.40      0.38        10
           1       0.00      0.00      0.00         7
           2       0.18      0.33      0.24         6
           3       0.25      0.25      0.25         8
           4       0.00      0.00      0.00         4

    accuracy                           0.23        35
   macro avg       0.16      0.20      0.17        35
weighted avg       0.19      0.23      0.21        35



## Klasifikasi Menggunakan KNN hasil GLCM 90 Degree

In [14]:
file_name = "../notebook/result/glcm_features_90_degree.csv" 
df = pd.read_csv(file_name)
print(df.head)

<bound method NDFrame.head of      contrast_90  homogeneity_90  correlation_90  energy_90  label
0      48.913055        0.794652        0.969663   0.152971      0
1      91.133534        0.843336        0.888134   0.160843      0
2      23.898751        0.857397        0.989142   0.179878      0
3      31.965485        0.835359        0.979239   0.143162      0
4      72.747191        0.813642        0.950845   0.207206      0
..           ...             ...             ...        ...    ...
170    39.884627        0.851571        0.911330   0.241795      4
171   109.498149        0.681933        0.926154   0.140547      4
172   177.542720        0.773784        0.872122   0.186789      4
173   145.566399        0.807589        0.828749   0.173143      4
174    68.719565        0.826630        0.951161   0.181924      4

[175 rows x 5 columns]>


In [15]:
# Pisahkan fitur (X) dan label kelas (y)
X = df.drop('label', axis=1) 
y = df['label']

In [16]:
# Bagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [17]:
# Inisialisasi model KNN
knn = KNeighborsClassifier(n_neighbors=4) 
# Latih model KNN
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [18]:
# Lakukan prediksi pada data uji
y_pred = knn.predict(X_test)

In [19]:
# Hitung dan tampilkan confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Tampilkan laporan klasifikasi
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(classification_rep)


Confusion Matrix:
[[3 3 2 1 1]
 [2 2 2 0 1]
 [1 2 1 1 1]
 [3 2 2 0 1]
 [0 1 1 0 2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.30      0.32        10
           1       0.20      0.29      0.24         7
           2       0.12      0.17      0.14         6
           3       0.00      0.00      0.00         8
           4       0.33      0.50      0.40         4

    accuracy                           0.23        35
   macro avg       0.20      0.25      0.22        35
weighted avg       0.19      0.23      0.21        35



## Klasifikasi Menggunakan KNN hasil GLCM 135 Degree

In [20]:
file_name = "../notebook/result/glcm_features_135_degree.csv"
df = pd.read_csv(file_name)
print(df.head)

<bound method NDFrame.head of      contrast_135  homogeneity_135  correlation_135  energy_135  label
0      173.844805         0.805667         0.892292    0.156058      0
1       63.004537         0.865046         0.922682    0.166606      0
2       89.052386         0.837714         0.959530    0.176169      0
3      106.450134         0.835703         0.930860    0.143655      0
4      172.692754         0.811668         0.883358    0.205275      0
..            ...              ...              ...         ...    ...
170     41.435853         0.850722         0.907877    0.242152      4
171     65.079142         0.700208         0.956084    0.141597      4
172    216.525195         0.755399         0.844033    0.182967      4
173    103.922029         0.794540         0.877733    0.169511      4
174    113.289900         0.812024         0.919455    0.178411      4

[175 rows x 5 columns]>


In [21]:
# Pisahkan fitur (X) dan label kelas (y)
X = df.drop('label', axis=1) 
y = df['label']

In [22]:
# Bagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [23]:
# Inisialisasi model KNN
knn = KNeighborsClassifier(n_neighbors=4)  
# Latih model KNN
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [24]:
# Lakukan prediksi pada data uji
y_pred = knn.predict(X_test)

In [25]:
# Hitung dan tampilkan confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Tampilkan laporan klasifikasi
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(classification_rep)


Confusion Matrix:
[[7 2 1 0 0]
 [1 3 2 0 1]
 [1 3 0 2 0]
 [3 2 0 1 2]
 [1 1 0 0 2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.70      0.61        10
           1       0.27      0.43      0.33         7
           2       0.00      0.00      0.00         6
           3       0.33      0.12      0.18         8
           4       0.40      0.50      0.44         4

    accuracy                           0.37        35
   macro avg       0.31      0.35      0.31        35
weighted avg       0.33      0.37      0.33        35



## Klasifikasi semua arah GLCM menggunakan KKNN

In [26]:
file_name = "../notebook/result/output_feature_extraction_GLCM.csv" 
df = pd.read_csv(file_name)
print(df.head)

<bound method NDFrame.head of      contrast_0  contrast_45  contrast_90  contrast_135  homogeneity_0  \
0    173.844805     0.805667     0.892292      0.156058     221.599345   
1     63.004537     0.865046     0.922682      0.166606     136.791043   
2     89.052386     0.837714     0.959530      0.176169     106.956690   
3    106.450134     0.835703     0.930860      0.143655     149.727050   
4    172.692754     0.811668     0.883358      0.205275     308.617062   
..          ...          ...          ...           ...            ...   
170   41.435853     0.850722     0.907877      0.242152      78.559334   
171   65.079142     0.700208     0.956084      0.141597     136.775607   
172  216.525195     0.755399     0.844033      0.182967     340.062997   
173  103.922029     0.794540     0.877733      0.169511     186.203432   
174  113.289900     0.812024     0.919455      0.178411     174.928826   

     homogeneity_45  homogeneity_90  homogeneity_135  correlation_0  \
0         

In [27]:
# Pisahkan fitur (X) dan label kelas (y)
X = df.drop('label', axis=1) 
y = df['label']

In [28]:
# Bagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [29]:
# Inisialisasi model KNN
knn = KNeighborsClassifier(n_neighbors=4) 
# Latih model KNN
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [30]:
print(X_test.head())

     contrast_0  contrast_45  contrast_90  contrast_135  homogeneity_0  \
125   89.440981     0.916350     0.940683      0.349764     117.820080   
145  108.373055     0.834226     0.963145      0.168750     176.314415   
65    99.475307     0.903286     0.894444      0.251138     152.060011   
4    172.692754     0.811668     0.883358      0.205275     308.617062   
7    111.858205     0.809198     0.939915      0.134227     138.516046   

     homogeneity_45  homogeneity_90  homogeneity_135  correlation_0  \
125        0.890020        0.922114         0.339103      36.692609   
145        0.797856        0.940208         0.160396     105.487113   
65         0.872471        0.839159         0.238311      64.964426   
4          0.759290        0.792139         0.187381      72.747191   
7          0.760439        0.925796         0.122218      82.013133   

     correlation_45  correlation_90  correlation_135    energy_0  energy_45  \
125        0.914155        0.975666         0.347

In [31]:
# Lakukan prediksi pada data uji
y_pred = knn.predict(X_test)

In [32]:
# Hitung dan tampilkan confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Tampilkan laporan klasifikasi
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(classification_rep)


Confusion Matrix:
[[6 2 2 0 0]
 [3 2 2 0 0]
 [3 0 1 1 1]
 [1 2 1 4 0]
 [0 0 1 1 2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.46      0.60      0.52        10
           1       0.33      0.29      0.31         7
           2       0.14      0.17      0.15         6
           3       0.67      0.50      0.57         8
           4       0.67      0.50      0.57         4

    accuracy                           0.43        35
   macro avg       0.45      0.41      0.43        35
weighted avg       0.45      0.43      0.43        35

