In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

### Load Dataset Feature Extraction HSV Mean, Skewness, Entrophy, Standard Deviasi

In [2]:
# Baca dataset CSV yang berisi hasil perhitungan fitur HSV
dataset_path = '../notebook/result/output_feature_extraction_HSV.csv' 
df = pd.read_csv(dataset_path)

In [11]:
df.head()

H_mean     S_mean      V_mean  H_skewness  S_skewness  V_skewness  \
0  112.918556  25.083630  233.556561   -8.984022    5.166388   -5.116159   
1  102.019578   6.076716  239.601118   -2.936337    8.822647   -5.048020   
2  107.860592  49.071800  219.021018   -4.309712    5.606899   -4.171041   
3  107.707690  42.995309  214.469718   -6.700319    4.903321   -3.790741   
4  111.507190  21.193654  218.849183   -5.202897    5.463856   -4.667438   

   H_entropy  S_entropy  V_entropy      H_std      S_std      V_std   label  
0  15.930703  15.777923  15.926208   8.421821  18.594424  27.223275  Skala0  
1  13.755722  13.160871  13.811461  26.847181  12.564507  19.617937  Skala0  
2  13.813757  13.791267  13.794408   6.033221  12.621105  37.301510  Skala0  
3  13.812133  13.777719  13.802779   7.833227  13.849444  30.174435  Skala0  
4  13.812049  13.625900  13.804734   8.537049  18.484920  27.969296  Skala0

In [4]:
# Pisahkan fitur-fitur (atribut) dan label (kelas)
X = df.drop('label', axis=1)  # Atribut
y = df['label']  # Kelas

In [13]:
# Bagi data menjadi data pelatihan dan data pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)
print(X_test)

         H_mean     S_mean      V_mean  H_skewness  S_skewness  V_skewness  \
28   108.957347  21.478116  228.849707   -4.613958    5.003672   -5.150001   
0    112.918556  25.083630  233.556561   -8.984022    5.166388   -5.116159   
139  108.423686  22.537409  251.209923   -6.900028    5.715377   -7.924924   
166  104.052148  22.915012  223.193722   -3.269524    5.571240   -4.563150   
174  106.863420  45.861029  216.693520   -6.239178    7.048882   -4.940546   
3    107.707690  42.995309  214.469718   -6.700319    4.903321   -3.790741   
38    36.145684   7.879730  229.571654    0.616836    2.871679   -6.151655   
34   109.161141  51.630220  230.091209   -6.449218    6.070217   -4.778564   
82    97.144615  29.777537  246.108473   -4.519964    1.830639   -7.043834   
159  108.861552  16.348049  243.336444   -5.177627    8.218011   -5.742746   
35   113.176831  28.754019  229.992928   -8.442057    5.600563   -4.611075   
29   108.387316  18.134845  219.190473   -5.538913    6.931065  

In [6]:
# Mengambil jumlah data dalam X_test
jumlah_data_x_test = X_test.shape[0]

# Print jumlah data X_test
print("Jumlah data dalam X_test:", jumlah_data_x_test)

Jumlah data dalam X_test: 35


In [7]:
# Mengambil jumlah data dalam X_test
jumlah_data_x_train = X_train.shape[0]

# Print jumlah data X_test
print("Jumlah data dalam X_train:", jumlah_data_x_train)

Jumlah data dalam X_train: 140


In [8]:
# Inisialisasi dan latih model KNN
knn_model = KNeighborsClassifier(n_neighbors=4)  
knn_model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [9]:
# Prediksi kelas data pengujian
y_pred = knn_model.predict(X_test)
print(y_pred[:5])

['Skala0' 'Skala1' 'Skala2' 'Skala3' 'Skala4']


In [10]:
# Evaluasi performa model dengan confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Menampilkan laporan klasifikasi (classification report)
report = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(report)

Confusion Matrix:
[[6 1 0 0 0]
 [0 2 2 1 0]
 [1 1 2 1 0]
 [1 1 2 2 0]
 [2 1 0 3 6]]

Classification Report:
              precision    recall  f1-score   support

      Skala0       0.60      0.86      0.71         7
      Skala1       0.33      0.40      0.36         5
      Skala2       0.33      0.40      0.36         5
      Skala3       0.29      0.33      0.31         6
      Skala4       1.00      0.50      0.67        12

    accuracy                           0.51        35
   macro avg       0.51      0.50      0.48        35
weighted avg       0.61      0.51      0.53        35

