# Load Dataset Hasil Ekstraksi Fitur HSV dan GLCM

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
# Load the CSV data into a DataFrame
df = pd.read_csv('../notebook/result/output_combine_GLCM_HSV.csv')
df.head()

contrast_0  contrast_45  contrast_90  contrast_135  homogeneity_0  \
0  173.844805     0.805667     0.892292      0.156058     221.599345   
1   63.004537     0.865046     0.922682      0.166606     136.791043   
2   89.052386     0.837714     0.959530      0.176169     106.956690   
3  106.450134     0.835703     0.930860      0.143655     149.727050   
4  172.692754     0.811668     0.883358      0.205275     308.617062   

   homogeneity_45  homogeneity_90  homogeneity_135  correlation_0  \
0        0.771900        0.862952         0.149101      48.913055   
1        0.796055        0.832516         0.147934      91.133534   
2        0.796018        0.951538         0.161958      23.898751   
3        0.777069        0.902978         0.128966      31.965485   
4        0.759290        0.792139         0.187381      72.747191   

   correlation_45  ...    skew_h    skew_s    skew_v  entropy_h  entropy_s  \
0        0.794652  ... -8.979452  5.156686 -5.116159  15.930705  15.777227   
1        0.843336  ... -2.933976  8.831609 -5.048020  13.755710  13.190363   
2        0.857397  ... -4.336087  5.597002 -4.171041  13.813776  13.791269   
3        0.835359  ... -6.683743  4.919780 -3.790741  13.812129  13.777835   
4        0.813642  ... -5.207486  5.467912 -4.667438  13.812072  13.627053   

   entropy_v     std_h     std_s     std_v  label  
0  15.926208  0.046750  0.072982  0.106758      0  
1  13.811461  0.149127  0.049180  0.076933      0  
2  13.794408  0.033290  0.049505  0.146280      0  
3  13.802779  0.043550  0.054253  0.118331      0  
4  13.804734  0.047176  0.072431  0.109684      0  

[5 rows x 29 columns]

### Splitting Dataset

In [3]:
# Pisahkan fitur (X) dan label kelas (y)
X = df.drop('label', axis=1)  
y = df['label']

In [4]:
# Bagi data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

In [5]:
# Inisialisasi model KNN
knn = KNeighborsClassifier(n_neighbors=4)  
# Latih model KNN
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [6]:
# Lakukan prediksi pada data uji
y_pred = knn.predict(X_test)

In [7]:
# Hitung dan tampilkan confusion matrix
confusion = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion)

# Tampilkan laporan klasifikasi
classification_rep = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(classification_rep)


Confusion Matrix:
[[6 2 2 0 0]
 [3 2 2 0 0]
 [3 0 1 1 1]
 [1 2 1 4 0]
 [0 0 1 1 2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.46      0.60      0.52        10
           1       0.33      0.29      0.31         7
           2       0.14      0.17      0.15         6
           3       0.67      0.50      0.57         8
           4       0.67      0.50      0.57         4

    accuracy                           0.43        35
   macro avg       0.45      0.41      0.43        35
weighted avg       0.45      0.43      0.43        35

